### PR TITLE
Add buttons to get the app

### PR DESCRIPTION
**Pull request by Poussinou**
Buttons with links to F-Droid and Google Play Store

### CODE REVIEW

**Comment by schwabe** [comment]
Hey, I think it does not hurt to merge this. Can you sign the cla hub?

**Comment by schwabe** [comment]
Hey, I think it does not hurt to merge this. Can you sign the cla hub?

**Review by taweesakteejantuk66 — COMMENTED** [review]
good

**Comment by Poussinou** [comment]
I don't want to give my phone or anything else like this in CLA, maybe you can copy-paste the different lines I added, and close this PR?

**Comment by schwabe** [comment]
@Poussinou I will just your comment here as proof that your contribution is public domain, is that okay for you too?

**Comment by Poussinou** [comment]
Yep it's ok for me, my contribution is public domain

**Pull request merged**
